  import {
  MapPin,
  Trash2,
  Truck,
  Shield,
  Calendar,
  CreditCard,
} from "lucide-react"
  
  export const progressSteps = [
    { icon: MapPin, label: "Postcode", completed: true },
    { icon: Trash2, label: "Waste Type", completed: true },
    { icon: Truck, label: "Select Skip", active: true },
    { icon: Shield, label: "Permit Check", completed: false },
    { icon: Calendar, label: "Choose Date", completed: false },
    { icon: CreditCard, label: "Payment", completed: false },
  ]


 export const skipOptions = [
    {
      id: 1,
      name: "4 Yard Skip",
      capacity: "4 Yards",
      price: "£211",
      originalPrice: "£250",
      period: "14 day hire period",
      image: "/images/skip-4yard.jpg",
      roadAllowed: true,
      popular: false,
      description: "Perfect for small home projects",
      features: ["Household waste", "Garden waste", "Small renovations"],
    },
    {
      id: 2,
      name: "5 Yard Skip",
      capacity: "5 Yards",
      price: "£241",
      originalPrice: "£280",
      period: "14 day hire period",
      image: "/images/skip-5yard.jpg",
      roadAllowed: true,
      popular: true,
      description: "Most popular choice for home use",
      features: ["Kitchen renovations", "Bathroom refits", "General waste"],
    },
    {
      id: 3,
      name: "6 Yard Skip",
      capacity: "6 Yards",
      price: "£264",
      originalPrice: "£310",
      period: "14 day hire period",
      image: "/images/skip-6yard.jpg",
      roadAllowed: true,
      popular: false,
      description: "Great for medium-sized projects",
      features: ["Room clearances", "Garden landscaping", "Office clearouts"],
    },
    {
      id: 4,
      name: "8 Yard Skip",
      capacity: "8 Yards",
      price: "£302",
      originalPrice: "£350",
      period: "14 day hire period",
      image: "/images/skip-8yard.jpg",
      roadAllowed: true,
      popular: false,
      description: "Ideal for larger home projects",
      features: ["Large renovations", "Construction waste", "Bulky items"],
    },
    {
      id: 5,
      name: "10 Yard Skip",
      capacity: "10 Yards",
      price: "£341",
      originalPrice: "£390",
      period: "14 day hire period",
      image: "/images/skip-10yard.jpg",
      roadAllowed: false,
      popular: false,
      description: "Commercial grade capacity",
      features: ["Commercial projects", "Large clearances", "Heavy materials"],
    },
    {
      id: 6,
      name: "12 Yard Skip",
      capacity: "12 Yards",
      price: "£380",
      originalPrice: "£440",
      period: "14 day hire period",
      image: "/images/skip-12yard.jpg",
      roadAllowed: false,
      popular: false,
      description: "Maximum capacity option",
      features: ["Industrial use", "Major construction", "Bulk disposal"],
    },
  ]